version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: reachinbox-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reachinbox
    ports:
      - "5433:5432"
    volumes:
      - pgdata_reachinbox:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: reachinbox-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: reachinbox-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata_reachinbox:
  redisdata:
  esdata:
